/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofome6;

import javax.swing.JOptionPane;

/**
 *
 * @author Eleutério
 */
public class AtualizarTela extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarTela
     */
    public AtualizarTela() {
        super("Atualizar Produtos: ");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProdutoAtualizar = new javax.swing.JPanel();
        txtIdAtualizar = new javax.swing.JTextField();
        txtNomeAtualizar = new javax.swing.JTextField();
        txtQuantidadeAtualizar = new javax.swing.JTextField();
        BtnConfirmarAtualizar = new java.awt.Button();
        BtnVoltarAtualizar = new java.awt.Button();
        txtPrecoAtualizar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtProdutoAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar Produto: "));

        txtIdAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Id: "));

        txtNomeAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome: "));

        txtQuantidadeAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade: "));

        BtnConfirmarAtualizar.setLabel("Confirmar");
        BtnConfirmarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarAtualizarActionPerformed(evt);
            }
        });

        BtnVoltarAtualizar.setLabel("Voltar");
        BtnVoltarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarAtualizarActionPerformed(evt);
            }
        });

        txtPrecoAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço:  "));

        javax.swing.GroupLayout txtProdutoAtualizarLayout = new javax.swing.GroupLayout(txtProdutoAtualizar);
        txtProdutoAtualizar.setLayout(txtProdutoAtualizarLayout);
        txtProdutoAtualizarLayout.setHorizontalGroup(
            txtProdutoAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtProdutoAtualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVoltarAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnConfirmarAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(txtProdutoAtualizarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(txtProdutoAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 109, Short.MAX_VALUE))
        );
        txtProdutoAtualizarLayout.setVerticalGroup(
            txtProdutoAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(txtProdutoAtualizarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(txtIdAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(txtProdutoAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVoltarAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConfirmarAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(txtProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarAtualizarActionPerformed

        CRUDTela t = new CRUDTela();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarAtualizarActionPerformed

    private void BtnConfirmarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarAtualizarActionPerformed
                                                    
        try {
        int id = Integer.parseInt(txtIdAtualizar.getText());
        String nome = txtNomeAtualizar.getText();
        double quantidade = Double.parseDouble(txtQuantidadeAtualizar.getText());
        double preco = Double.parseDouble(txtPrecoAtualizar.getText());

        // 🔑 Aqui você precisa recuperar o usuario logado.
        // Simulando usuário logado:
        Usuario usuario = new Usuario("arthur", "1234"); 
        DAO dao = new DAO();
        //Integer usuarioId = dao.getUsuarioId(usuario);

        //if (usuarioId == null) {
        //    JOptionPane.showMessageDialog(null, "Erro: Usuário não encontrado.");
        //    return;
        //}

        // Criando o objeto Produto corretamente:
        Produto produto = new Produto(id, nome, quantidade, preco);

        // Atualizando no banco:
        dao.atualizar(produto);

        JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!!");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, insira valores válidos para Id, Quantidade e Preço.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Não foi possível atualizar o produto. Erro: " + e.getMessage());
    }

        

    }//GEN-LAST:event_BtnConfirmarAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnConfirmarAtualizar;
    private java.awt.Button BtnVoltarAtualizar;
    private javax.swing.JTextField txtIdAtualizar;
    private javax.swing.JTextField txtNomeAtualizar;
    private javax.swing.JTextField txtPrecoAtualizar;
    private javax.swing.JPanel txtProdutoAtualizar;
    private javax.swing.JTextField txtQuantidadeAtualizar;
    // End of variables declaration//GEN-END:variables
}
