/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofome6;

import javax.swing.JOptionPane;

/**
 *
 * @author Eleutério
 */
public class InserirTela extends javax.swing.JFrame {

    /**
     * Creates new form InserirTela
     */
    
   
    private int usuarioId;  // campo da classe

public InserirTela() {
    super("Inserir Produtos");
    initComponents();
    this.setLocationRelativeTo(null);
    this.usuarioId = -1;  // valor padrão
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produto = new javax.swing.JPanel();
        BtnVoltarInserir = new java.awt.Button();
        BtnConfirmarInserir = new java.awt.Button();
        txtNomeInserir = new javax.swing.JTextField();
        txtQuantidadeInserir = new javax.swing.JTextField();
        txtPrecoInserir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        produto.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir Produto:"));

        BtnVoltarInserir.setLabel("Voltar");
        BtnVoltarInserir.setName(""); // NOI18N
        BtnVoltarInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarInserirActionPerformed(evt);
            }
        });

        BtnConfirmarInserir.setLabel("Confirmar");
        BtnConfirmarInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarInserirActionPerformed(evt);
            }
        });

        txtNomeInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome: "));
        txtNomeInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInserirActionPerformed(evt);
            }
        });

        txtQuantidadeInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade: "));

        txtPrecoInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Preco: "));

        javax.swing.GroupLayout produtoLayout = new javax.swing.GroupLayout(produto);
        produto.setLayout(produtoLayout);
        produtoLayout.setHorizontalGroup(
            produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoLayout.createSequentialGroup()
                        .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQuantidadeInserir)
                            .addGroup(produtoLayout.createSequentialGroup()
                                .addGap(0, 129, Short.MAX_VALUE)
                                .addComponent(BtnVoltarInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(BtnConfirmarInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPrecoInserir))
                        .addGap(20, 20, 20))
                    .addGroup(produtoLayout.createSequentialGroup()
                        .addComponent(txtNomeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        produtoLayout.setVerticalGroup(
            produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVoltarInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BtnConfirmarInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarInserirActionPerformed
       CRUDTela t = new CRUDTela();
       t.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnVoltarInserirActionPerformed

    private void BtnConfirmarInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarInserirActionPerformed

        String nome = txtNomeInserir.getText();
        String quantidadeStr = txtQuantidadeInserir.getText();
        String precoStr = txtPrecoInserir.getText();
        
        try{
            
            double quantidade = Double.parseDouble(quantidadeStr);
            double preco = Double.parseDouble(precoStr);
            
            
            Produto produto = new Produto (nome,quantidade, preco);
            DAO dao = new DAO();
            dao.inserir(produto);
            JOptionPane.showMessageDialog(null,"Produto Inserido");
            
            txtNomeInserir.setText("");
            txtQuantidadeInserir.setText("");
            txtPrecoInserir.setText("");
        
        }catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(null, "Quantidade e preço precisam ser numeros válidos");
        }catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Não foi possível inserir: " + e.getMessage());
}

    }//GEN-LAST:event_BtnConfirmarInserirActionPerformed

    private void txtNomeInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnConfirmarInserir;
    private java.awt.Button BtnVoltarInserir;
    private javax.swing.JPanel produto;
    private javax.swing.JTextField txtNomeInserir;
    private javax.swing.JTextField txtPrecoInserir;
    private javax.swing.JTextField txtQuantidadeInserir;
    // End of variables declaration//GEN-END:variables
}
